lint:
  image: node:latest
  script:
    - git checkout $CI_COMMIT_BRANCH
    - yarn install
    - yarn lint
    - git config user.name metahkg-bot
    - git config user.email bot@metahkg.org
    - git commit -a -m lint || exit 0
    - git remote set-url origin https://wcyat:$gitlab_token@gitlab.com/metahkg/metahkg-links.git
    - git push origin $CI_COMMIT_BRANCH
  rules:
    - if: $CI_COMMIT_AUTHOR != "metahkg-bot <bot@metahkg.org>"

docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - apk add nodejs-current
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --build-arg REACT_APP_build=$CI_COMMIT_SHORT_SHA --pull -t "$CI_REGISTRY_IMAGE/$CI_COMMIT_BRANCH:latest" -t "$CI_REGISTRY_IMAGE/$CI_COMMIT_BRANCH:$CI_COMMIT_SHORT_SHA" -t "$CI_REGISTRY_IMAGE/$CI_COMMIT_BRANCH:$(node -e 'console.log(require("./package.json").version)')" .
    - docker push "$CI_REGISTRY_IMAGE/$CI_COMMIT_BRANCH:latest"
    - docker push "$CI_REGISTRY_IMAGE/$CI_COMMIT_BRANCH:$CI_COMMIT_SHORT_SHA"
    - docker push "$CI_REGISTRY_IMAGE/$CI_COMMIT_BRANCH:$(node -e 'console.log(require("./package.json").version)')"
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile

tagging:
  image: alpine:latest
  stage: deploy
  before_script:
    - apk add git
  script:
    - git config --global user.name metahkg-bot
    - git config --global user.email bot@metahkg.org
    - tag=$(cat package.json | grep version | grep -Eo "[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+")
    - if [ $CI_COMMIT_BRANCH = "dev" ]; then tag=${tag}-dev; fi;
    - git tag "$tag"
    - git push --tags https://root:$gitlab_token@$CI_SERVER_HOST/$CI_PROJECT_PATH.git HEAD:${CI_COMMIT_BRANCH}
  rules:
    - if: $CI_COMMIT_AUTHOR != "metahkg-bot <bot@metahkg.org>" && ($CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "master")

include:
  - template: Auto-DevOps.gitlab-ci.yml

sast:
  stage: test
